language: php
php:
  - 5.5
  - 5.6
  - 7.0
  - hhvm

before_install:
  - composer self-update

install:
  - composer install --no-interaction --prefer-source

matrix:
  allow_failures:
    - php: hhvm
    - php: 7.0

addons:
    code_climate:
        repo_token: 132909497dc319666376e1c9a7a94967f78cbd1a7006c23b53331940cf3ee252
